package com.nousresearch.hermes.tenant.audit;

/**
 * 审计事件类型
 */
public enum AuditEvent {
    // 租户生命周期
    TENANT_CREATED,
    TENANT_DESTROYED,
    TENANT_SUSPENDED,
    TENANT_RESUMED,
    ORG_MANAGEMENT_ROLE_CREATED,
    ORG_MANAGEMENT_ROLE_UPDATED,
    ORG_MANAGEMENT_ROLE_DELETED,
    ORG_MANAGEMENT_TEAM_CREATED,
    ORG_MANAGEMENT_TEAM_UPDATED,
    ORG_MANAGEMENT_TEAM_DELETED,
    
    // Agent 生命周期
    AGENT_CREATED,
    AGENT_DESTROYED,

    // Control Center governance actions
    CONTROL_INTENT_REPLAYED,
    CONTROL_INTENT_REROUTED,
    CONTROL_AGENT_OVERRIDE_CHANGED,
    CONTROL_ACTION_DENIED,
    CONTROL_BROWSER_ACTION,
    CONTROL_BROWSER_ACTION_DENIED,
    CONTROL_BROWSER_BRIDGE_CONFIGURED,
    CONTROL_BROWSER_HEALTH_CHECK,
    CONTROL_BROWSER_CONTRACT_TEST,
    CONTROL_BROWSER_PROVIDER_PROBE,
    CONTROL_BROWSER_APPROVAL_REQUESTED,
    CONTROL_BROWSER_APPROVAL_APPROVED,
    CONTROL_BROWSER_APPROVAL_REJECTED,
    CONTROL_DELEGATED_TASK_SUBMITTED,
    CONTROL_DELEGATED_TASK_VERIFIED,
    CONTROL_DELEGATED_TASK_EXECUTED,
    
    // 文件操作
    FILE_READ,
    FILE_WRITE,
    FILE_DELETE,
    
    // Skill 操作
    SKILL_CREATED,
    SKILL_UPDATED,
    SKILL_DELETED,
    SKILL_INSTALLED,
    SKILL_UNINSTALLED,
    SKILL_SHARED,
    
    // 代码执行
    CODE_EXECUTED,
    CODE_BLOCKED,
    CODE_TIMEOUT,
    
    // 终端命令
    TERMINAL_COMMAND,
    
    // 工具调用
    TOOL_CALLED,
    
    // Skill 执行
    SKILL_EXECUTED,
    
    // 配额
    QUOTA_EXCEEDED,
    
    // 安全
    SECURITY_VIOLATION,
    AUTHENTICATION_FAILED,

    // 网络请求
    NETWORK_REQUEST,
    NETWORK_RESPONSE,
    NETWORK_BLOCKED
}
